import Head from "next/head";
import Navbar from "../../components/navbar"
import Heroslider from "../../components/Home/Heroslider";
import Herobottom from "../../components/Home/Herobottom";
import Welcome from "../../components/Home/Welcome";
import Whyus from "../../components/Home/Whyus";
import Ourcourses from "../../components/Home/Ourcourses";
import Counters from '../../components/Home/Counters'
import Events from '../../components/Home/Events'
import { Inter } from "next/font/google";
import News from "../../components/Home/News";
import Testimonials from "../../components/Home/testimonials";
import Footer from "../../components/Home/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>APRIORI EDUCATION SOLUTIONS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <div>
          <Navbar />
          <Heroslider />
          <Herobottom />
          <Welcome />
          <Whyus />
          <Ourcourses />
          <Counters />
          <Events />
          <Testimonials />
          <News />
          <Footer />
        </div>
      </main>
    </>
  );
}
