import fs from 'node:fs';
const file = 'src/data/sat/mockContent/mathBankFactoryRemediatedUnique.js';
let s = fs.readFileSync(file, 'utf8');
if (s.includes('// Batch M linear construction remediation v2')) process.exit(0);
if (!s.includes("./batchMLinearConstructionV2.js")) s = s.replace("import { DIFFICULTY_REQUIREMENTS, PSAT_CEILING_RULES } from './batchMRemediationBlueprint.js';", "import { DIFFICULTY_REQUIREMENTS, PSAT_CEILING_RULES } from './batchMRemediationBlueprint.js';\nimport { buildBatchMLinearV2 } from './batchMLinearConstructionV2.js';");
function rb(a,b,r){const i=s.indexOf(a);if(i<0)throw new Error('missing '+a);const j=s.indexOf(b,i+a.length);if(j<0)throw new Error('missing '+b);s=s.slice(0,i)+r+s.slice(j);}
rb("  // Batch M linear difficulty/reuse remediation v1\n  if (skill === 'Linear relationships' || skill === 'Linear functions') {","  if (skill === 'Systems of linear equations' || skill === 'Linear equations') {","  // Batch M linear construction remediation v2\n  if (skill === 'Linear relationships' || skill === 'Linear functions') return buildBatchMLinearV2(question, o, 'function');\n\n");
rb("  if (skill === 'Equivalent linear representations' || skill === 'Linear representations' || skill === 'Linear functions and representations') {","  // Preserve the existing strategic construction branches below.","  if (skill === 'Equivalent linear representations' || skill === 'Linear representations' || skill === 'Linear functions and representations') return buildBatchMLinearV2(question, o, 'representation');\n\n");
const a="  // Use a 10-item difficulty lane (30% easy / 50% medium / 20% hard)\n  // so each source skill has materially broader coverage of the frozen\n  // target difficulty distribution without weakening the difficulty gate.\n  const difficultyLane = ['easy', 'easy', 'easy', 'medium', 'medium', 'medium', 'medium', 'medium', 'hard', 'hard'];\n  let difficulty = difficultyLane[occurrence % difficultyLane.length];";
const b="  const linearSkills = new Set(['Linear relationships', 'Linear functions', 'Equivalent linear representations', 'Linear representations', 'Linear functions and representations']);\n  const preserveConstructedLinearDifficulty = linearSkills.has(String(question.skill || ''));\n  let difficulty = preserveConstructedLinearDifficulty ? question.difficulty : ['easy', 'easy', 'easy', 'medium', 'medium', 'medium', 'medium', 'medium', 'hard', 'hard'][occurrence % 10];";
if(!s.includes(a))throw new Error('missing difficulty lane');s=s.replace(a,b);fs.writeFileSync(file,s,'utf8');console.log('Applied Batch M linear construction remediation v2.');